# Site settings
title: Charlie Lee
author: Charlie Lee
description: >
  Charlie Lee is a British developer currently based at the University of Sheffield.
  This website contains the projects, films and music he has created.
footer_text: "&copy; 2017 Charlie Lee"
navigation:
- text: Home
  url: /
- text: Contact
  url: contact
permalink: /:year/:month/:title/

# Collections
collections:
  category_pages:
    output: true
    permalink: /category/:path/
  feeds:
    output: true
    permalink: /feed/:path/
  projects:
    output: true
    permalink: /project/:path/

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
gems:
  - jekyll-redirect-from